---
title: "Production mensuelle de bière en Australie"
author: "___"
date: "___"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
SciViews::R
library(pastecs)
```

## Objectif

Explorer une série temporelle relative à la production de bière en Australie. La production mensuelle de bière en mégalitres est enregistrée mensuellement depuis 1956. D'après vous, quelles sont les grandes caractéristiques de cette séries chronologique ?

## Analyse

<!--% Importez le jeu de données `beer.csv` du dossier `data`. Transformez-le en objet `ts` et nommez-le beer_ts. -->

```{r import}

```

<!--% Écrivez le code qui renvoie le début, la fin et la fréquence de cette série. Commentez vos observations en une phrase. -->

```{r ts}

```

<!--% Représentez graphiquement l'autocorrélation de cette série. Décrivez ensuite ce que vous observez en maximum deux phrases. -->

```{r acf}

```

<!--% Calculez des statistiques glissantes pertinentes pour cette série. Réalisez ensuite un graphique de ces statistiques. -->

```{r statslide}

```

<!-- Interprétez le graphique des statistiques glissantes en maximum trois phrases.-->

<!--% Étudiez la tendance générale de votre série via bootstrap (y compris le graphique).-->

```{r trendtest}

```

<!-- Interprétez le test de tendance générale en maximum deux phrases.-->

<!--% Effectuez, si cela est justifié, une analyse spectrale pertinente de votre série (spectrogramme lissé). Le code prérempli permet de stationnariser la séries (il sera étudié au module 5 et vous n'avez pas besoin de le comprendre juste accepter que la série est stationnarisée). L'analyse spectrale peut être réalisée sur beer_stat ensuite. -->

```{r spectrum}
beer_stat <- extract(tsd(beer_ts, s.window = 13, trend = TRUE), components = 2)

```

<!-- Interprétez l'analyse spectrale réalisée en maximum deux phrases.-->

<!--% Réaliser un graphique en boites de dispersion parallèles des la composante stationnarisée beer_stat (une boite de dispersion par mois) et interprétez-le en une phrase. -->

```{r boxplot}

```

## Conclusions

<!--% Ajoutez ici en 3 phrases maximum les caractéristiques importantes de cette série spatio-temporelle. -->
