---
title: "Patient schizophrène sous traitement"
author: "___"
date: "___"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
SciViews::R
library(pastecs)
```

## Objectif

Étudiez l'efficacité d'un médicament sur la réduction de l'activité cérébrale schizophrénique chez un même patient suivi quotidiennement en clinique psychiatrique pendant plusieurs mois. Le médicament n'est administré qu'à partir du 60^ème^ jour de son entrée en clinique.

## Analyse

<!--% Importez le jeu de données `schizo.tsv` qui est dans le dossier `data`. Transformez-le en objet `ts` que vous nommerez `schizo_ts`. -->

```{r import}

```

<!--% Écrivez le code qui renvoie le début, la fin et la fréquence de cette série. Commentez vos observations en une phrase. -->

```{r ts}

```

<!--% Représentez graphiquement l'autocorrélation de cette série. Décrivez ensuite ce que vous observez en maximum deux phrases. -->

```{r acf}

```

<!--% Calculez des statistiques glissantes pertinentes pour cette série. Réalisez ensuite un graphique de ces statistiques. -->

```{r statslide}

```

<!-- Interprétez le graphique des statistiques glissantes en maximum trois phrases.-->

<!--% Étudiez la tendance générale de votre série via bootstrap (y compris le graphique).-->

```{r trendtest}

```

<!-- Interprétez le test de tendance générale en maximum deux phrases.-->

<!--% Effectuez, si cela est justifié, une analyse spectrale pertinente de votre série (spectrogramme lissé). Le code prérempli permet de stationnariser la séries (il sera étudié au module 5 et vous n'avez pas besoin de le comprendre juste accepter que la série est stationnarisée). L'analyse spectrale peut être réalisée sur schizo_stat ensuite. -->

```{r spectrum}
# Stationnarisation de la série
schizo_stat <- extract(tsd(schizo_ts, method = "diff"), components = 1)

```

<!-- Interprétez l'analyse spectrale réalisée en maximum deux phrases.-->

## Conclusions

<!--% Ajoutez ici en 3 phrases maximum les caractéristiques importantes de cette série spatio-temporelle. -->
